### ISSUE TITLE
Status Codes missing from 'Delivery Reports'

### ISSUE THREAD

**Issue by Liam-PVTL** [messagemedia/documentation#11]
Please visit this link: https://messagemedia.github.io/documentation/#tag/Delivery-Reports

Under 'delivery reports' the final dot point reads:

> Status Code: A status code which provides additional information about the message status:

But doesn't follow it up with the actual codes (as the colon after 'status' would imply). 

Can these codes be found anywhere?

**Comment by MrJackDaly** [comment]
These status codes are now visible in the Delivery Reports documentation.

**Comment by Liam-PVTL** [comment]
Nice, thanks!
